version: '3.8'

services:
    ollama:
        image: ollama/ollama:latest
        container_name: ollama
        ports:
            - "11434:11434"
        volumes:
            - ./docker_data/ollama:/root/.ollama
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: 1
                          capabilities: [gpu]
        restart: always
        
    qdrant:
        image: qdrant/qdrant:latest 
        container_name: qdrant 
        ports:
            - "6333:6333" 
        volumes:
            - ./docker_data/qdrant:/qdrant/storage